version: '3.8'

services:
  honeypot-ssh:
    image: cowrie/cowrie
    ports:
      - "22:2222"

  honeypot-vnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    ports:
      - "5900:5900"

  honeypot-db-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  honeypot-db-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  honeypot-medical:
    build: .
    ports:
      - "104:104"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    restart: always

volumes:
  mongo_data: